name: Build cphc
run-name: ${{ gitea.actor }} Build CPHC Values
on: [push]

env:
  DOCKER_HOST: tcp://${{ env.HOSTNAME }}:2376
  DOCKER_CERT_PATH: /certs/client
  DOCKER_TLS_VERIFY: "1"

jobs:
  Build-Packages:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v4

      - run: apt update

      - run: apt install -y docker.io

      - run: sleep 2d

      - run: docker cp $(docker container ls -q | tail -n 1 | awk '{print $1}')

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: https://github.com/docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "git.jlscode.com/jesse/cphc-values-builder:${{gitea.sha}},git.jlscode.com/jesse/cphc-values-builder:latest"
