name: Build cphc
run-name: ${{ gitea.actor }} Build CPHC Values
on: [push]

jobs:
  Build-Packages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pwd
      - run: docker build -t git.jlscode.com/jesse/cphc-values-builder:latest .
      - run: docker login git.jlscode.com -u $USERNAME -p $PASSWORD
        env:
          USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - run: docker push git.jlscode.com/jesse/cphc-values-builder:latest
